apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    app: frontend 
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: frontend 

