apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: "8080"
    interval: 10s

