name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash
        # Inform a working directory if .tf files are not in the root folder
        working-directory: ./Terraform-infra 
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: /tmp/terraform-plan
        
      - name: Decrypt GCR_KEY
        run: |
          echo "${{ secrets.GCR_KEY }}" | base64 -d > /tmp/gcr-key.json
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
         cli_config_credentials_token: /tmp/gcr-key.json

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply /tmp/terraform-plan/tfplan.out
        env:
          GOOGLE_CREDENTIALS:  /tmp/gcr-key.json
