name: Terraform Workflow

on:
  push:
    paths:
      - 'Terraform-infra/**'

jobs:
  terraform_init_and_plan:
    name: Terraform Init and Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # Inform a working directory if .tf files are not in the root folder
        working-directory: ./Terraform-infra 
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Decrypt GCR_KEY
      run: |
          echo "${{ secrets.GCR_KEY }}" | base64 -d > /tmp/gcr-key.json

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: /tmp/gcr-key.json

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS:  /tmp/gcr-key.json
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS:  /tmp/gcr-key.json
    # This step creates a shared workspace for subsequent jobs
    - name: Set up workspace
      uses: actions/checkout@v2

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        # Inform a working directory if .tf files are not in the root folder
        working-directory: ./Terraform-infra 
        
    # Depend on the first job to ensure it runs after Terraform init and plan
    needs: terraform_init_and_plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
    - name: Decrypt GCR_KEY
      run: |
          echo "${{ secrets.GCR_KEY }}" | base64 -d > /tmp/gcr-key.json

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: /tmp/gcr-key.json

    # This step copies the initialized Terraform state from the previous job
    - name: Copy Terraform state from previous job
      uses: actions/checkout@v2
      with:
        path: terraform_state
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS:  /tmp/gcr-key.json
    - name: Terraform Apply
      run: terraform apply -var-file=production.tfvars -state=terraform_state/terraform.tfstate
      env:
        GOOGLE_CREDENTIALS:  /tmp/gcr-key.json
